// File này Tèo code tự động.
// Đại ca quăng ảnh vào tram_nhap_hang/anh_tap_doc rồi chạy Tool nha!

export const TAP_DOC_DATA = [
  { word: 'bàn chải', image: require('../assets/images/anh_tap_doc/bàn chải.png') },
  { word: 'báo đốm', image: require('../assets/images/anh_tap_doc/báo đốm.png') },
  { word: 'bão', image: require('../assets/images/anh_tap_doc/bão.png') },
  { word: 'bóng bay', image: require('../assets/images/anh_tap_doc/bóng bay.png') },
  { word: 'bút chì', image: require('../assets/images/anh_tap_doc/bút chì.png') },
  { word: 'bọ cánh cứng', image: require('../assets/images/anh_tap_doc/bọ cánh cứng.png') },
  { word: 'bọ hung', image: require('../assets/images/anh_tap_doc/bọ hung.png') },
  { word: 'bọ ngựa', image: require('../assets/images/anh_tap_doc/bọ ngựa.png') },
  { word: 'chiếc mũ', image: require('../assets/images/anh_tap_doc/chiếc mũ.png') },
  { word: 'chuồn chuồn', image: require('../assets/images/anh_tap_doc/chuồn chuồn.png') },
  { word: 'chìa khóa', image: require('../assets/images/anh_tap_doc/chìa khóa.png') },
  { word: 'com-pa', image: require('../assets/images/anh_tap_doc/com-pa.png') },
  { word: 'con bò', image: require('../assets/images/anh_tap_doc/con bò.png') },
  { word: 'con bọ xít', image: require('../assets/images/anh_tap_doc/con bọ xít.png') },
  { word: 'con bớm', image: require('../assets/images/anh_tap_doc/con bớm.png') },
  { word: 'con chó', image: require('../assets/images/anh_tap_doc/con chó.png') },
  { word: 'con cuốn chiếu', image: require('../assets/images/anh_tap_doc/con cuốn chiếu.png') },
  { word: 'con cừu', image: require('../assets/images/anh_tap_doc/con cừu.png') },
  { word: 'con dế', image: require('../assets/images/anh_tap_doc/con dế.png') },
  { word: 'con gà', image: require('../assets/images/anh_tap_doc/con gà.png') },
  { word: 'con heo', image: require('../assets/images/anh_tap_doc/con heo.png') },
  { word: 'con hổ', image: require('../assets/images/anh_tap_doc/con hổ.png') },
  { word: 'con khỉ', image: require('../assets/images/anh_tap_doc/con khỉ.png') },
  { word: 'con kiến', image: require('../assets/images/anh_tap_doc/con kiến.png') },
  { word: 'con muỗi', image: require('../assets/images/anh_tap_doc/con muỗi.png') },
  { word: 'con mèo', image: require('../assets/images/anh_tap_doc/con mèo.png') },
  { word: 'con nhện', image: require('../assets/images/anh_tap_doc/con nhện.png') },
  { word: 'con ong', image: require('../assets/images/anh_tap_doc/con ong.png') },
  { word: 'con ruồi', image: require('../assets/images/anh_tap_doc/con ruồi.png') },
  { word: 'con rùa', image: require('../assets/images/anh_tap_doc/con rùa.png') },
  { word: 'con rết', image: require('../assets/images/anh_tap_doc/con rết.png') },
  { word: 'con thỏ', image: require('../assets/images/anh_tap_doc/con thỏ.png') },
  { word: 'con trâu', image: require('../assets/images/anh_tap_doc/con trâu.png') },
  { word: 'con tằm', image: require('../assets/images/anh_tap_doc/con tằm.png') },
  { word: 'con ve chó', image: require('../assets/images/anh_tap_doc/con ve chó.png') },
  { word: 'con ve', image: require('../assets/images/anh_tap_doc/con ve.png') },
  { word: 'con voi', image: require('../assets/images/anh_tap_doc/con voi.png') },
  { word: 'con vẹt', image: require('../assets/images/anh_tap_doc/con vẹt.png') },
  { word: 'con vịt', image: require('../assets/images/anh_tap_doc/con vịt.png') },
  { word: 'con ốc sên', image: require('../assets/images/anh_tap_doc/con ốc sên.png') },
  { word: 'cá chép', image: require('../assets/images/anh_tap_doc/cá chép.png') },
  { word: 'cá cơm', image: require('../assets/images/anh_tap_doc/cá cơm.png') },
  { word: 'cá hề', image: require('../assets/images/anh_tap_doc/cá hề.png') },
  { word: 'cá koi', image: require('../assets/images/anh_tap_doc/cá koi.png') },
  { word: 'cá mập', image: require('../assets/images/anh_tap_doc/cá mập.png') },
  { word: 'cá ngừ', image: require('../assets/images/anh_tap_doc/cá ngừ.png') },
  { word: 'cá voi', image: require('../assets/images/anh_tap_doc/cá voi.png') },
  { word: 'cá vàng', image: require('../assets/images/anh_tap_doc/cá vàng.png') },
  { word: 'cá đuối', image: require('../assets/images/anh_tap_doc/cá đuối.png') },
  { word: 'cái chổi', image: require('../assets/images/anh_tap_doc/cái chổi.png') },
  { word: 'cái cặp', image: require('../assets/images/anh_tap_doc/cái cặp.png') },
  { word: 'cái kẹo', image: require('../assets/images/anh_tap_doc/cái kẹo.png') },
  { word: 'cây cầu', image: require('../assets/images/anh_tap_doc/cây cầu.png') },
  { word: 'cây cổ thụ', image: require('../assets/images/anh_tap_doc/cây cổ thụ.png') },
  { word: 'cơn bão', image: require('../assets/images/anh_tap_doc/cơn bão.png') },
  { word: 'cầu vồng', image: require('../assets/images/anh_tap_doc/cầu vồng.png') },
  { word: 'cột điện', image: require('../assets/images/anh_tap_doc/cột điện.png') },
  { word: 'cục tẩy', image: require('../assets/images/anh_tap_doc/cục tẩy.png') },
  { word: 'gió', image: require('../assets/images/anh_tap_doc/gió.png') },
  { word: 'gương soi', image: require('../assets/images/anh_tap_doc/gương soi.png') },
  { word: 'gấu bông', image: require('../assets/images/anh_tap_doc/gấu bông.png') },
  { word: 'kỳ nhông', image: require('../assets/images/anh_tap_doc/kỳ nhông.png') },
  { word: 'la bàn', image: require('../assets/images/anh_tap_doc/la bàn.png') },
  { word: 'lợn vòi', image: require('../assets/images/anh_tap_doc/lợn vòi.png') },
  { word: 'máy tính bỏ túi', image: require('../assets/images/anh_tap_doc/máy tính bỏ túi.png') },
  { word: 'máy ảnh', image: require('../assets/images/anh_tap_doc/máy ảnh.png') },
  { word: 'mưa', image: require('../assets/images/anh_tap_doc/mưa.png') },
  { word: 'mặt trời', image: require('../assets/images/anh_tap_doc/mặt trời.png') },
  { word: 'nhà cửa', image: require('../assets/images/anh_tap_doc/nhà cửa.png') },
  { word: 'nồi cơm điện', image: require('../assets/images/anh_tap_doc/nồi cơm điện.png') },
  { word: 'nồi đất', image: require('../assets/images/anh_tap_doc/nồi đất.png') },
  { word: 'phấn và bảng', image: require('../assets/images/anh_tap_doc/phấn và bảng.png') },
  { word: 'quyển vở', image: require('../assets/images/anh_tap_doc/quyển vở.png') },
  { word: 'quả táo', image: require('../assets/images/anh_tap_doc/quả táo.png') },
  { word: 'sách', image: require('../assets/images/anh_tap_doc/sách.png') },
  { word: 'sư tử', image: require('../assets/images/anh_tap_doc/sư tử.png') },
  { word: 'sương mù', image: require('../assets/images/anh_tap_doc/sương mù.png') },
  { word: 'sấm sét', image: require('../assets/images/anh_tap_doc/sấm sét.png') },
  { word: 'tháp', image: require('../assets/images/anh_tap_doc/tháp.png') },
  { word: 'thước kẻ', image: require('../assets/images/anh_tap_doc/thước kẻ.png') },
  { word: 'ti vi', image: require('../assets/images/anh_tap_doc/ti vi.png') },
  { word: 'tuyết', image: require('../assets/images/anh_tap_doc/tuyết.png') },
  { word: 'tàu hỏa', image: require('../assets/images/anh_tap_doc/tàu hỏa.png') },
  { word: 'ô tô', image: require('../assets/images/anh_tap_doc/ô tô.png') },
  { word: 'điện thoại', image: require('../assets/images/anh_tap_doc/điện thoại.png') },
  { word: 'đèn ngủ', image: require('../assets/images/anh_tap_doc/đèn ngủ.png') },
  { word: 'đèn đường', image: require('../assets/images/anh_tap_doc/đèn đường.png') },
  { word: 'đười ươi', image: require('../assets/images/anh_tap_doc/đười ươi.png') },
  { word: 'đập nước', image: require('../assets/images/anh_tap_doc/đập nước.png') },
  { word: 'đền chùa', image: require('../assets/images/anh_tap_doc/đền chùa.png') },
  { word: 'đồng hồ', image: require('../assets/images/anh_tap_doc/đồng hồ.png') },
  { word: 'ấm trà', image: require('../assets/images/anh_tap_doc/ấm trà.png') },
];
