// File này được Tèo viết tự động bằng Tool.
// Đại ca quăng ảnh vào thư mục assets/images/anh_tap_doc rồi chạy lệnh node để cập nhật nha!

export const TAP_DOC_DATA = [
  { word: 'bàn chải', image: require('../assets/images/anh_tap_doc/bàn chải.png') },
  { word: 'bão', image: require('../assets/images/anh_tap_doc/bão.png') },
  { word: 'chìa khóa', image: require('../assets/images/anh_tap_doc/chìa khóa.png') },
  { word: 'con bò', image: require('../assets/images/anh_tap_doc/con bò.png') },
  { word: 'con chó', image: require('../assets/images/anh_tap_doc/con chó.png') },
  { word: 'con cừu', image: require('../assets/images/anh_tap_doc/con cừu.png') },
  { word: 'con gà', image: require('../assets/images/anh_tap_doc/con gà.png') },
  { word: 'con heo', image: require('../assets/images/anh_tap_doc/con heo.png') },
  { word: 'con khỉ', image: require('../assets/images/anh_tap_doc/con khỉ.png') },
  { word: 'con mèo', image: require('../assets/images/anh_tap_doc/con mèo.png') },
  { word: 'con trâu', image: require('../assets/images/anh_tap_doc/con trâu.png') },
  { word: 'con vịt', image: require('../assets/images/anh_tap_doc/con vịt.png') },
  { word: 'cây cầu', image: require('../assets/images/anh_tap_doc/cây cầu.png') },
  { word: 'cây cổ thụ', image: require('../assets/images/anh_tap_doc/cây cổ thụ.png') },
  { word: 'cơn bão', image: require('../assets/images/anh_tap_doc/cơn bão.png') },
  { word: 'cầu vồng', image: require('../assets/images/anh_tap_doc/cầu vồng.png') },
  { word: 'cột điện', image: require('../assets/images/anh_tap_doc/cột điện.png') },
  { word: 'gió', image: require('../assets/images/anh_tap_doc/gió.png') },
  { word: 'la bàn', image: require('../assets/images/anh_tap_doc/la bàn.png') },
  { word: 'máy ảnh', image: require('../assets/images/anh_tap_doc/máy ảnh.png') },
  { word: 'mưa', image: require('../assets/images/anh_tap_doc/mưa.png') },
  { word: 'mặt trời', image: require('../assets/images/anh_tap_doc/mặt trời.png') },
  { word: 'nhà cửa', image: require('../assets/images/anh_tap_doc/nhà cửa.png') },
  { word: 'nồi đất', image: require('../assets/images/anh_tap_doc/nồi đất.png') },
  { word: 'sách', image: require('../assets/images/anh_tap_doc/sách.png') },
  { word: 'sương mù', image: require('../assets/images/anh_tap_doc/sương mù.png') },
  { word: 'sấm sét', image: require('../assets/images/anh_tap_doc/sấm sét.png') },
  { word: 'tháp', image: require('../assets/images/anh_tap_doc/tháp.png') },
  { word: 'tuyết', image: require('../assets/images/anh_tap_doc/tuyết.png') },
  { word: 'tàu hỏa', image: require('../assets/images/anh_tap_doc/tàu hỏa.png') },
  { word: 'điện thoại', image: require('../assets/images/anh_tap_doc/điện thoại.png') },
  { word: 'đèn đường', image: require('../assets/images/anh_tap_doc/đèn đường.png') },
  { word: 'đập nước', image: require('../assets/images/anh_tap_doc/đập nước.png') },
  { word: 'đền chùa', image: require('../assets/images/anh_tap_doc/đền chùa.png') },
  { word: 'đồng hồ', image: require('../assets/images/anh_tap_doc/đồng hồ.png') },
  { word: 'ấm trà', image: require('../assets/images/anh_tap_doc/ấm trà.png') },
];
