// ipa/scripts/setup_be_hoc_toan.js
const { Client } = require('pg');

// Anh hai nhớ thay MẬT_KHẨU vào chuỗi này nhé, giữ nguyên connection string của tài khoản free là được!
const connectionString = 'postgresql://postgres.vgoymfsyzdjgvhiddxum:Nguyenthanhduong1511@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres';

const client = new Client({
  connectionString: connectionString,
  ssl: { rejectUnauthorized: false }
});

const setupQuery = `
  -- 1. Xây móng: Tạo bảng dữ liệu học tập cho bé Phương Linh
  CREATE TABLE IF NOT EXISTS be_hoc_toan_data (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id uuid REFERENCES auth.users NOT NULL,
      max_limit integer DEFAULT 10,
      total_score integer DEFAULT 0,
      updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
  );

  -- 2. Bật hàng rào bảo mật (Row Level Security)
  ALTER TABLE be_hoc_toan_data ENABLE ROW LEVEL SECURITY;

  -- 3. Ban hành luật: Tài khoản của ai thì người đó được xem, thêm, sửa
  -- Luật XEM
  CREATE POLICY "Chủ tài khoản được xem" ON be_hoc_toan_data 
      FOR SELECT USING (auth.uid() = user_id);

  -- Luật THÊM
  CREATE POLICY "Chủ tài khoản được thêm" ON be_hoc_toan_data 
      FOR INSERT WITH CHECK (auth.uid() = user_id);

  -- Luật SỬA
  CREATE POLICY "Chủ tài khoản được sửa" ON be_hoc_toan_data 
      FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
      
  -- Luật XÓA
  CREATE POLICY "Chủ tài khoản được xóa" ON be_hoc_toan_data 
      FOR DELETE USING (auth.uid() = user_id);
`;

async function setupDatabase() {
  try {
    console.log("⏳ Tèo đang xách vữa xây bảng 'be_hoc_toan_data' cho bé Phương Linh...");
    await client.connect();
    
    await client.query(setupQuery);
    
    console.log("✅ Ngon lành cành đào anh hai ơi! Bảng mới đã sẵn sàng, bảo mật RLS cũng đã được kích hoạt.");
  } catch (err) {
    console.error("❌ Ây da, có lỗi xây dựng rồi:", err);
  } finally {
    await client.end();
  }
}

setupDatabase();